name: 🚀 Deploy to Hostinger via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    # Set up SSH Key for deployment
    - name: Set up SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.HOSTINGER_SSH_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -p ${{ secrets.HOSTINGER_PORT }} ${{ secrets.HOSTINGER_HOST }} >> ~/.ssh/known_hosts

    # Create .env file with secret keys from GitHub Secrets
    - name: Create .env file from secrets
      run: |
          echo "VITE_SUPABASE_URL=${{ secrets.VITE_SUPABASE_URL }}" >> .env
          echo "VITE_SUPABASE_KEY=${{ secrets.VITE_SUPABASE_KEY }}" >> .env
          echo "VITE_RAZORPAY_KEY_ID=${{ secrets.VITE_RAZORPAY_KEY_ID }}" >> .env
          echo "VITE_RAZORPAY_KEY_SECRET=${{ secrets.VITE_RAZORPAY_KEY_SECRET }}" >> .env
          echo "VITE_WEB3FORMS_KEY=${{ secrets.VITE_WEB3FORMS_KEY }}" >> .env

    # Install dependencies and build the project
    - name: Build the project
      run: |
            npm install
            npm run build

    # Deploy build output to Hostinger
    - name: Deploy via SCP
      run: |
              scp -P ${{ secrets.HOSTINGER_PORT }} -r ./dist/* ${{ secrets.HOSTINGER_USERNAME }}@${{ secrets.HOSTINGER_HOST }}:/home/u478829093/public_html/
